In [21]:
#loading the dataset and removing additional info column

import pandas as pd
data=pd.read_csv('used_car_dataset.csv')
data.drop(columns=['AdditionInfo'],inplace=True)

data.columns

Index(['Brand', 'model', 'Year', 'Age', 'kmDriven', 'Transmission', 'Owner',
       'FuelType', 'PostedDate', 'AskPrice'],
      dtype='object')

In [27]:
data.shape

(9582, 10)

In [28]:
data.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AskPrice
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"₹ 1,95,000"
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"₹ 3,75,000"
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"₹ 1,84,999"
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,"₹ 5,65,000"
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"₹ 6,85,000"

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9582 entries, 0 to 9581
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         9582 non-null   object
 1   model         9582 non-null   object
 2   Year          9582 non-null   int64
 3   Age           9582 non-null   int64
 4   kmDriven      9535 non-null   object
 5   Transmission  9582 non-null   object
 6   Owner         9582 non-null   object
 7   FuelType      9582 non-null   object
 8   PostedDate    9582 non-null   object
 9   AskPrice      9582 non-null   object
dtypes: int64(2), object(8)
memory usage: 748.7+ KB

In [6]:
data.drop(columns=['PostedDate'],inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9582 entries, 0 to 9581
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         9582 non-null   object
 1   model         9582 non-null   object
 2   Year          9582 non-null   int64
 3   Age           9582 non-null   int64
 4   kmDriven      9535 non-null   object
 5   Transmission  9582 non-null   object
 6   Owner         9582 non-null   object
 7   FuelType      9582 non-null   object
 8   AskPrice      9582 non-null   object
dtypes: int64(2), object(7)
memory usage: 673.9+ KB

In [7]:
data['FuelType'].value_counts()

FuelType
Diesel        3840
Petrol        3822
Hybrid/CNG    1920
Name: count, dtype: int64

In [8]:
data['Transmission'].value_counts()

Transmission
Manual       4800
Automatic    4782
Name: count, dtype: int64

In [9]:
data['Owner'].value_counts()

Owner
first     4800
second    4782
Name: count, dtype: int64

In [22]:
# since the above columns have only 2 or 3 types of values instead of using one hot encoding or binary classifier we will 
# manually classify them with values 0,1,2

data['Transmission']=data['Transmission'].map({'Manual':0,'Automatic':1})
data['Owner']=data['Owner'].map({'first':0,'second':1})
data['FuelType']=data['FuelType'].map({'Petrol':0,'Diesel':1,'Hybrid/CNG':2})

data.head(5)

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AskPrice
0,Honda,City,2001,23,"98,000 km",0,1,0,Nov-24,"₹ 1,95,000"
1,Toyota,Innova,2009,15,190000.0 km,0,1,1,Jul-24,"₹ 3,75,000"
2,Volkswagen,VentoTest,2010,14,"77,246 km",0,0,1,Nov-24,"₹ 1,84,999"
3,Maruti Suzuki,Swift,2017,7,"83,500 km",0,1,1,Nov-24,"₹ 5,65,000"
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",1,0,0,Nov-24,"₹ 6,85,000"

In [23]:
data.drop(columns=['PostedDate'],inplace=True)
data.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,AskPrice
0,Honda,City,2001,23,"98,000 km",0,1,0,"₹ 1,95,000"
1,Toyota,Innova,2009,15,190000.0 km,0,1,1,"₹ 3,75,000"
2,Volkswagen,VentoTest,2010,14,"77,246 km",0,0,1,"₹ 1,84,999"
3,Maruti Suzuki,Swift,2017,7,"83,500 km",0,1,1,"₹ 5,65,000"
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",1,0,0,"₹ 6,85,000"

In [25]:
# now we will convert the columns kmdriven and askprice to pure float/int columns
data['AskPrice']=data['AskPrice'].str.replace(r'[₹,\s]','',regex=True).astype(int)
data.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,AskPrice
0,Honda,City,2001,23,"98,000 km",0,1,0,195000
1,Toyota,Innova,2009,15,190000.0 km,0,1,1,375000
2,Volkswagen,VentoTest,2010,14,"77,246 km",0,0,1,184999
3,Maruti Suzuki,Swift,2017,7,"83,500 km",0,1,1,565000
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",1,0,0,685000

In [26]:
cleaned_text=data['kmDriven'].str.replace(r'[^\d.]','',regex=True)
data['kmDriven']=pd.to_numeric(cleaned_text,errors='coerce')

data.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,AskPrice
0,Honda,City,2001,23,98000.0,0,1,0,195000
1,Toyota,Innova,2009,15,190000.0,0,1,1,375000
2,Volkswagen,VentoTest,2010,14,77246.0,0,0,1,184999
3,Maruti Suzuki,Swift,2017,7,83500.0,0,1,1,565000
4,Maruti Suzuki,Baleno,2019,5,45000.0,1,0,0,685000

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9582 entries, 0 to 9581
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         9582 non-null   object
 1   model         9582 non-null   object
 2   Year          9582 non-null   int64
 3   Age           9582 non-null   int64
 4   kmDriven      9535 non-null   float64
 5   Transmission  9582 non-null   int64
 6   Owner         9582 non-null   int64
 7   FuelType      9582 non-null   int64
 8   AskPrice      9582 non-null   int64
dtypes: float64(1), int64(6), object(2)
memory usage: 673.9+ KB

In [31]:
data['Brand'].value_counts().count()

np.int64(39)

In [33]:
# now we will create one column which will include both brand and model
data['brand_model']=data['Brand']+' '+data['model']
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9582 entries, 0 to 9581
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         9582 non-null   object
 1   model         9582 non-null   object
 2   Year          9582 non-null   int64
 3   Age           9582 non-null   int64
 4   kmDriven      9535 non-null   float64
 5   Transmission  9582 non-null   int64
 6   Owner         9582 non-null   int64
 7   FuelType      9582 non-null   int64
 8   AskPrice      9582 non-null   int64
 9   brand_model   9582 non-null   object
dtypes: float64(1), int64(6), object(3)
memory usage: 748.7+ KB

In [34]:
data['brand_model'].value_counts()

brand_model
Honda City               330
Maruti Suzuki Wagon-R    311
Maruti Suzuki Swift      283
Hyundai Creta            260
Maruti Suzuki Ertiga     249
                        ...
Mahindra Nuvosport         1
Mercedes-Benz AMG A35      1
BMW X5 M                   1
Ashok Leyland Stile        1
Maserati Gran Turismo      1
Name: count, Length: 401, dtype: int64

In [35]:
data['brand_model'].value_counts().count()

np.int64(401)

In [36]:
data.describe()

,Year,Age,kmDriven,Transmission,Owner,FuelType,AskPrice
count,9582.000000,9582.000000,9535.000000,9582.000000,9582.000000,9582.000000,9.582000e+03
mean,2016.361094,7.638906,70605.891453,0.499061,0.499061,0.801503,1.063609e+06
std,4.087226,4.087226,56308.596299,0.500025,0.500025,0.748269,1.658495e+06
min,1986.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.500000e+04
25%,2014.000000,5.000000,43000.000000,0.000000,0.000000,0.000000,3.610000e+05
50%,2017.000000,7.000000,65000.000000,0.000000,0.000000,1.000000,5.990000e+05
75%,2019.000000,10.000000,86000.000000,1.000000,1.000000,1.000000,1.125000e+06
max,2024.000000,38.000000,980002.000000,1.000000,1.000000,2.000000,4.250000e+07

In [37]:
data.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,AskPrice,brand_model
0,Honda,City,2001,23,98000.0,0,1,0,195000,Honda City
1,Toyota,Innova,2009,15,190000.0,0,1,1,375000,Toyota Innova
2,Volkswagen,VentoTest,2010,14,77246.0,0,0,1,184999,Volkswagen VentoTest
3,Maruti Suzuki,Swift,2017,7,83500.0,0,1,1,565000,Maruti Suzuki Swift
4,Maruti Suzuki,Baleno,2019,5,45000.0,1,0,0,685000,Maruti Suzuki Baleno

In [ ]:
# this is the dataset we will be using for model training
# to use it in a different file we will export it is a csv file

data.to_csv('cleaned_used_car_dataset.csv',index=False)